#!/usr/bin/env -S uv run --script
# /// script
# requires-python = ">=3.11"
# dependencies = []
# ///
"""Generate deck/styles/tokens.css from the shared tokens in ../tokens.toml.

Proxima's stylesheet scopes accents and tones to <html>; a deck needs them on
each slide, so one slide can take another accent or projection. This writes the
same values as attribute selectors on the slide wrapper (`.px`).

Usage:
    uv run deck/scripts/tokens.py           # rewrite deck/styles/tokens.css
    uv run deck/scripts/tokens.py --check   # exit 1 if the file is out of date
"""

from __future__ import annotations

import sys
import tomllib
from pathlib import Path

DECK = Path(__file__).resolve().parent.parent
TOKENS = DECK.parent / "tokens.toml"
OUT = DECK / "styles" / "tokens.css"

STATES = ("mint", "amber", "rose", "sky")


def rgba(hex_colour: str, alpha: float) -> str:
    h = hex_colour.lstrip("#")
    r, g, b = (int(h[i : i + 2], 16) for i in (0, 2, 4))
    return f"rgba({r},{g},{b},{alpha:g})"


def block(selector: str, lines: list[str]) -> str:
    body = "\n".join(f"  {line}" for line in lines)
    return f"{selector} {{\n{body}\n}}\n"


def tone_block(tone: str, t: dict) -> str:
    n = t["neutral"][tone]
    lines = [
        f"--void: {n['void']};",
        f"--panel: {n['panel']};",
        f"--panel-2: {n['panel_2']};",
        f"--ink-hi: {n['ink_hi']};",
        f"--ink-mid: {n['ink_mid']};",
        f"--ink-low: {n['ink_low']};",
        f"--ch-neutral: {t['chart']['neutral'][tone]};",
    ]
    for name in STATES:
        s = t["state"][tone][name]
        lines.append(
            f"--{name}: {s['text']}; --{name}-fill: {rgba(s['base'], s['fill'])}; --{name}-line: {rgba(s['text'], s['line'])};"
        )
    return block(f'.px[data-tone="{tone}"]', lines)


def accent_block(name: str, tone: str, t: dict) -> str:
    a = t["accent"][name][tone]
    light = t["accent"][name]["light"]
    charts = " ".join(f"--ch-{i + 1}: {c};" for i, c in enumerate(a["charts"]))
    lines = [
        f"--accent: {a['accent']};",
        f"--accent-deep: {a['deep']};",
        f"--accent-ink: {a['ink']};",
        f"--accent-glow: {rgba(a['glow']['color'], a['glow']['alpha'])};",
        charts,
        # The tonal ramp is built in OKLCH from the light accent, as Centauri does,
        # so hue holds across the ramp in both tones.
        f"--px-ramp-src: {light['accent']};",
    ]
    return block(f'.px[data-tone="{tone}"][data-accent="{name}"]', lines)


def render(t: dict) -> str:
    out = [
        f"/* Generated by deck/scripts/tokens.py from tokens.toml {t['version']}; do not edit by hand.",
        "   Shared Proxima–Centauri tokens, scoped to a slide so accent and projection",
        "   can change per slide. Local deck tokens are in deck.css. */",
        "",
    ]
    for tone in ("dark", "light"):
        out.append(tone_block(tone, t))
    for name in t["accent"]:
        for tone in ("dark", "light"):
            out.append(accent_block(name, tone, t))
    return "\n".join(out)


def main(argv: list[str]) -> int:
    with TOKENS.open("rb") as f:
        tokens = tomllib.load(f)
    css = render(tokens)
    if "--check" in argv:
        current = OUT.read_text() if OUT.exists() else ""
        if current != css:
            print(f"{OUT.relative_to(DECK.parent)} is out of date; run uv run deck/scripts/tokens.py", file=sys.stderr)
            return 1
        return 0
    OUT.write_text(css)
    print(f"wrote {OUT.relative_to(DECK.parent)}")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
