#!/usr/bin/env -S uv run --script
# /// script
# requires-python = ">=3.11"
# dependencies = []
# ///
"""Regenerate the shared token blocks in css/proxima.css from tokens.toml.

Only the text between the `tokens:begin` and `tokens:end` markers is replaced.
Everything outside the markers is Proxima's own and is left untouched.

Usage:
    uv run scripts/tokens.py           # rewrite css/proxima.css
    uv run scripts/tokens.py --check   # exit 1 if the file is out of date or the
                                       # deck's major.minor differs from tokens.toml
"""

from __future__ import annotations

import json
import sys
import tomllib
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
TOKENS = ROOT / "tokens.toml"
CSS = ROOT / "css" / "proxima.css"
DECK_PACKAGE = ROOT / "deck" / "package.json"

BEGIN = "/* tokens:begin"
END = "/* tokens:end */"

# Proxima's own type parameters. Headings: body * phi ^ ((6 - N) / K).
# The small tier steps down from body at half the heading step.
BODY_PX = 14.5
K = 2



def rgba(hex_colour: str, alpha: float) -> str:
    h = hex_colour.lstrip("#")
    r, g, b = (int(h[i : i + 2], 16) for i in (0, 2, 4))
    return f"rgba({r},{g},{b},{alpha:g})"


def px(value: float) -> str:
    return f"{value:.1f}".rstrip("0").rstrip(".") + "px"


def type_scale(phi: float) -> list[str]:
    step = phi ** (1 / K)
    half = step ** 0.5
    out = [f"--fs-h{n}: {px(BODY_PX * step ** (6 - n))};" for n in range(1, 7)]
    out.append(f"--fs-body: {px(BODY_PX)};")
    out.append(f"--fs-lg: {px(BODY_PX * half)};")
    out += [
        f"--fs-sm: {px(BODY_PX / half)};",
        f"--fs-xs: {px(BODY_PX / half ** 2)};",
        f"--fs-2xs: {px(BODY_PX / half ** 3)};",
    ]
    return out


def neutrals(n: dict) -> list[str]:
    return [
        f"--void: {n['void']};",
        f"--panel: {n['panel']};",
        f"--panel-2: {n['panel_2']};",
        f"--ink-hi: {n['ink_hi']};",
        f"--ink-mid: {n['ink_mid']};",
        f"--ink-low: {n['ink_low']};",
    ]


def states(s: dict) -> list[str]:
    return [
        f"--{name}: {v['text']}; --{name}-fill: {rgba(v['base'], v['fill'])}; "
        f"--{name}-line: {rgba(v['text'], v['line'])};"
        for name, v in s.items()
    ]


def accent(a: dict, fog: str | None) -> list[str]:
    out = [
        f"--accent: {a['accent']};",
        f"--accent-deep: {a['deep']};",
        f"--accent-ink: {a['ink']};",
        f"--accent-glow: {rgba(a['glow']['color'], a['glow']['alpha'])};",
    ]
    out.append(" ".join(f"--ch-{i}: {c};" for i, c in enumerate(a["charts"], 1)))
    if fog:
        out.append(f"--fog-accent: {fog};")
    return out


def block(selector: str, lines: list[str]) -> str:
    body = "\n".join(f"  {line}" for line in lines)
    return f"{selector} {{\n{body}\n}}"


def generate(t: dict) -> str:
    acc = t["accent"]
    dark = (
        neutrals(t["neutral"]["dark"])
        + accent(acc["indigo"]["dark"], acc["indigo"]["light"]["deep"])
        + states(t["state"]["dark"])
        + [f"--ch-neutral: {t['chart']['neutral']['dark']};"]
        + type_scale(t["scale"]["phi"])
    )
    light = (
        neutrals(t["neutral"]["light"])
        + accent(acc["indigo"]["light"], None)
        + states(t["state"]["light"])
        + [f"--ch-neutral: {t['chart']['neutral']['light']};"]
    )
    # Fixed swatches for accent pickers: each shows its own accent whatever is active.
    dark += [f"--swatch-{name}: {modes['dark']['accent']};" for name, modes in acc.items()]
    parts = [block(":root", dark), block("html.theme-light", light)]
    for name, modes in acc.items():
        if name == "indigo":
            continue
        parts.append(block(f"html.accent-{name}", accent(modes["dark"], modes["light"]["deep"])))
        parts.append(block(f"html.accent-{name}.theme-light", accent(modes["light"], None)))
    header = (
        f"{BEGIN} (generated by scripts/tokens.py from tokens.toml "
        f"{t['version']}; do not edit by hand) */"
    )
    return "\n".join([header, *parts, END])


def main() -> int:
    t = tomllib.loads(TOKENS.read_text(encoding="utf-8"))
    css = CSS.read_text(encoding="utf-8")
    start, stop = css.find(BEGIN), css.find(END)
    if start < 0 or stop < 0:
        print(f"error: {CSS}: token markers not found", file=sys.stderr)
        return 2
    updated = css[:start] + generate(t) + css[stop + len(END) :]
    if "--check" in sys.argv[1:]:
        if updated != css:
            print(f"{CSS} is out of date; run scripts/tokens.py", file=sys.stderr)
            return 1
        # Proxima and Centauri share major.minor; the deck carries Proxima's version.
        deck = json.loads(DECK_PACKAGE.read_text(encoding="utf-8"))["version"]
        if deck.split(".")[:2] != t["version"].split(".")[:2]:
            print(
                f"{DECK_PACKAGE} is {deck} but tokens.toml is {t['version']}; "
                "major.minor must match",
                file=sys.stderr,
            )
            return 1
        return 0
    CSS.write_text(updated, encoding="utf-8")
    print(f"wrote {CSS.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
